## Data Set - vaccination data by country

In [1]:
import pandas as pd
import numpy as np
path = 'C:\\Users\\kjhm\\Documents\\QMB3302\\Data Sets\\vaccination data.csv'
seg = pd.read_csv(path)
seg.head(43439)

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,daily_vaccinations_per_million
0,Afghanistan,AFG,2/22/2021,0.0,0.0,NaN,NaN,NaN,NaN,0.00,0.00,NaN,NaN,NaN
1,Afghanistan,AFG,2/23/2021,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0
2,Afghanistan,AFG,2/24/2021,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0
3,Afghanistan,AFG,2/25/2021,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0
4,Afghanistan,AFG,2/26/2021,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43434,Zimbabwe,ZWE,8/24/2021,3889424.0,2382059.0,1507365.0,NaN,60413.0,62638.0,25.77,15.78,9.99,NaN,4150.0
43435,Zimbabwe,ZWE,8/25/2021,4015517.0,2453229.0,1562288.0,NaN,126093.0,67597.0,26.61,16.25,10.35,NaN,4479.0
43436,Zimbabwe,ZWE,8/26/2021,NaN,NaN,NaN,NaN,NaN,60688.0,NaN,NaN,NaN,NaN,4021.0
43437,Zimbabwe,ZWE,8/27/2021,4075995.0,2491680.0,1584315.0,NaN,NaN,53784.0,27.01,16.51,10.50,NaN,3564.0
43438,Zimbabwe,ZWE,8/28/2021,4110354.0,2513053.0,1597301.0,NaN,34359.0,51016.0,27.24,16.65,10.58,NaN,3380.0

In [3]:
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns

## Our data set contains global vaccination data regarding Covid-19. Our group chose this data set due to its high relevance to the current events and its direct impact on our lives. We found the data to be interesting particularly when comparing one country to another.

## Features of the data:

In [2]:
seg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43439 entries, 0 to 43438
Data columns (total 14 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   location                             43439 non-null  object
 1   iso_code                             43439 non-null  object
 2   date                                 43439 non-null  object
 3   total_vaccinations                   25214 non-null  float64
 4   people_vaccinated                    24232 non-null  float64
 5   people_fully_vaccinated              21158 non-null  float64
 6   total_boosters                       513 non-null    float64
 7   daily_vaccinations_raw               21211 non-null  float64
 8   daily_vaccinations                   43172 non-null  float64
 9   total_vaccinations_per_hundred       25214 non-null  float64
 10  people_vaccinated_per_hundred        24232 non-null  float64
 11  people_fully_vaccinated_per_hundred  21158 non-null  float64
 12  total_boosters_per_hundred           513 non-null    float64
 13  daily_vaccinations_per_million       43172 non-null  float64
dtypes: float64(11), object(3)
memory usage: 4.6+ MB

## After reviewing the data info and the set in its entirety, we removed the data that was not available reducing the data set from 43439 rows, 14 columns to 18280 rows, 12 columns.

In [3]:
seg.dropna()

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,daily_vaccinations_per_million
2343,Asia,OWID_ASI,6/30/2021,1.907441e+09,1.117657e+09,3.826218e+08,298841.0,26561418.0,31479630.0,40.76,23.88,8.18,0.01,6727.0
2344,Asia,OWID_ASI,7/1/2021,1.940588e+09,1.129037e+09,3.855761e+08,559413.0,33147600.0,31023925.0,41.47,24.13,8.24,0.01,6630.0
2345,Asia,OWID_ASI,7/2/2021,1.965228e+09,1.132271e+09,3.875399e+08,908595.0,24639559.0,29498995.0,42.00,24.20,8.28,0.02,6304.0
2346,Asia,OWID_ASI,7/3/2021,1.991445e+09,1.141391e+09,3.924643e+08,1025325.0,26217115.0,28486269.0,42.56,24.39,8.39,0.02,6087.0
2347,Asia,OWID_ASI,7/4/2021,2.009793e+09,1.147507e+09,3.947059e+08,1362949.0,18348344.0,27006333.0,42.95,24.52,8.43,0.03,5771.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43025,World,OWID_WRL,8/24/2021,5.049527e+09,2.999932e+09,1.934223e+09,12207901.0,44314538.0,35044000.0,64.12,38.09,24.56,0.16,4450.0
43026,World,OWID_WRL,8/25/2021,5.092489e+09,3.015711e+09,1.946612e+09,12609237.0,42962635.0,35903400.0,64.67,38.29,24.72,0.16,4559.0
43027,World,OWID_WRL,8/26/2021,5.136240e+09,3.090383e+09,2.071441e+09,13022835.0,43750435.0,37120750.0,65.22,39.24,26.30,0.17,4714.0
43028,World,OWID_WRL,8/27/2021,5.182764e+09,3.108159e+09,2.085117e+09,13320850.0,46524001.0,38394876.0,65.81,39.47,26.48,0.17,4876.0
43029,World,OWID_WRL,8/28/2021,5.213176e+09,3.118470e+09,2.091593e+09,13427944.0,30411769.0,38591622.0,66.20,39.60,26.56,0.17,4901.0

Some interesting things to note about our dataset include the sheer lack of data regarding our particular topic of global Covid-19 vaccinations. When we reduced the rows in our data set to clean up the non-complete values, we noticed that a lot of the countries were cut such as Afghanistan (our first country prior to the 'dropna()' function). As far as global trends, it is still relatively early into the vaccination process so access to vaccines around the world is limited in those countries where as the US, vaccines were developed and distributed early.

Original Data retrieved from:
https://www.kaggle.com/priteshraj10/covid-vaccination-all-countries-data

In [ ]:
daily = seg['daily_vaccinations'].to_numpy()
booster = seg['Income'].to_numpy()

plt.scatter(age, income, color = 'purple')
plt.title('Relationship:Age and income')
plt.xlabel('Age')
plt.ylabel('Income');
plt.xlim(10,90)